<?php

declare(strict_types=1);

namespace D4np\Utils\Tests\Engine;

/**
 * The database engines the behavioural suites can be pointed at (issue #110, ADR-0071).
 *
 * The cases are the **PDO driver names**, not names of our own, because that is what
 * {@see \D4np\Utils\Database\Identifier::forDriver()} switches on and what
 * {@see \D4np\Utils\Database\DatabaseConnection::driver()} reports. A separate vocabulary here
 * would be one more mapping to keep true, and the first thing it would get wrong is the case the
 * library itself dispatches on.
 *
 * The DDL vocabulary below is deliberately tiny — three column shapes, which is everything the
 * five converted suites use. A general schema builder would be a second, untested product living
 * in the test tree; what these suites need is that the *same table* exists on three engines.
 */
enum Engine: string
{
    case Sqlite = 'sqlite';
    case MySql = 'mysql';
    case PostgreSql = 'pgsql';

    /**
     * The engine a PDO DSN addresses — everything before the first `:`.
     *
     * An unrecognised prefix is a configuration error rather than a default, because the
     * defaulting version of this method silently runs the whole leg against SQLite and reports
     * success for an engine nobody tested.
     */
    public static function fromDsn(string $dsn): self
    {
        $prefix = \strstr($dsn, ':', true);

        return self::tryFrom($prefix === false ? $dsn : $prefix)
            ?? throw new \RuntimeException(\sprintf(
                'The DSN "%s" does not name an engine this harness knows. Expected one of: %s.',
                $dsn,
                \implode(', ', \array_map(static fn (self $e): string => $e->value . ':…', self::cases())),
            ));
    }

    /**
     * The PDO extension this engine needs, by the name `extension_loaded()` uses.
     */
    public function extension(): string
    {
        return 'pdo_' . $this->value;
    }

    /**
     * A human name for failure messages, so a red leg says which engine it was.
     */
    public function label(): string
    {
        return match ($this) {
            self::Sqlite => 'SQLite',
            self::MySql => 'MySQL',
            self::PostgreSql => 'PostgreSQL',
        };
    }

    /**
     * An auto-assigning integer primary key.
     *
     * Auto-assigning rather than caller-supplied because SQLite's `INTEGER PRIMARY KEY` *is* an
     * alias for the rowid and fills itself in — so the suites written against SQLite insert rows
     * with no `id` and expect one to appear. Reproducing that on the other two engines is what
     * keeps those tests testing the gateway rather than the schema. Both forms below still accept
     * an explicit id (`AUTO_INCREMENT` always does; `BY DEFAULT AS IDENTITY` is the identity
     * variant that does, as opposed to `ALWAYS`).
     */
    public function autoKey(): string
    {
        return match ($this) {
            self::Sqlite => 'INTEGER PRIMARY KEY',
            self::MySql => 'INT AUTO_INCREMENT PRIMARY KEY',
            self::PostgreSql => 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
        };
    }

    /**
     * A variable-length text column, compared **byte for byte**.
     *
     * The collation is pinned on MySQL and nowhere else, and the reason is worth stating because
     * it looks like the harness papering over a difference. MySQL 8's server default,
     * `utf8mb4_0900_ai_ci`, is case- and accent-insensitive: under it `WHERE name = 'ada'` matches
     * a stored `'Ada'`, while SQLite's `BINARY` and PostgreSQL's `C`-derived defaults do not. That
     * divergence is real, and it is *pinned by its own test* in {@see DialectTest} rather than
     * discovered thirty times over as unexplained failures in suites whose subject is injection
     * binding and DTO projection. Fixture schemas therefore ask for the deterministic collation,
     * and exactly one test asks for the default one.
     */
    public function text(): string
    {
        return match ($this) {
            self::MySql => 'TEXT COLLATE utf8mb4_bin',
            default => 'TEXT',
        };
    }

    /**
     * A plain integer column.
     */
    public function integer(): string
    {
        return match ($this) {
            self::MySql => 'INT',
            default => 'INTEGER',
        };
    }

    /**
     * Render one of the three shapes above from the vocabulary the suites write.
     *
     * @param 'key'|'text'|'int' $shape
     */
    public function column(string $shape): string
    {
        return match ($shape) {
            'key' => $this->autoKey(),
            'text' => $this->text(),
            'int' => $this->integer(),
            default => throw new \RuntimeException(\sprintf(
                'Unknown column shape "%s"; the harness knows key, text and int.',
                $shape,
            )),
        };
    }
}
